
export const en = {
  welcomeTo: "Welcome to",
  slogan: "Where your mental health is the priority.",
  description: "Space dedicated to mental health and making appointments with specialists in the area. One step closer, without leaving home.",
  login: "LogIn",
  register: "Register",
  or: "or",
  conditions1: "By continuing, you are agreeing to the",
  conditions2: "terms and conditions",
  conditions3: "of the application.",
  loginIncorrect: "Your email or password is incorrect. Please try again.",
  doesNotHasAccount: "Don't have an account?",
  email: "Email",
  password: "Password",
  accountType: "What kind of account are you going to use?",
  pacient: "Pacient",
  specialist: "Especialist",
  registerOf: "Register of",
  name: "Name",
  lastName: "LastName",
  idCard: "Identification Number",
  mustContainIdCard: "Must contain 11 numbers.",
  incorrectEmail: "Incorrect email.",
  includePassword: "Must include more than 8 characters.",
  mustContainPassword: "Must contain at least one uppercase letter [A-Z], one lowercase letter [a-z], one number [0-9], and one special character [@$!%*?&]",
  confirmPassword: "Confirm the password",
  noCoincidencePassword: "Passwords do not match.",
  hasAccount: "Already have an account?",
  reunions: "Meetings",
  needReunion: "Do you need another meeting?",
  firstAppointment: "Nothing to show for now! \n Schedule your first appointment to view information here. :)",
  scheduleAppointment: "Schedule an appointment",
  hasEmergency: "Do you have an emergency? \n Contact one of our available experts.",
  takeAppointmentNow: "Have an appointment now",
  nothingToSee: "Nothing to show for now! \nIf you haven't already, fill out your profile so patients can learn more about you and book appointments.",
  meetingDetails: "Meeting Details",
  date: "Date",
  sessionTime: "Session time",
  duration: "Duration",
  minutes: "Minutes",
  participants: "Participants",
  appointmentDescription: "Description",
  joinMeeting: "Join the meeting",
  askDeleteArticle: "Do you want to delete this article?",
  deleteArticle: "Delete Article",
  modifyArticle: "Edit Article",
  addArticle: "Add Article",
  cancel: "Cancel",
  videocall: "Video call",
  audiocall: "Audio Call",
  writeAMessage: "Write a message",
  otherUserGotOut: "The counterpart user has left this meeting",
  incomingVideocall: "Incoming Video Call",
  incomingAudiocall: "Incoming audio call",
  chatAdvice: "Messages shared in this chat are confidential. No one outside the conversation can read or decrypt them.",
  connecting: "Connecting",
  waitingForSomebody: "Waiting for someone else to join",
  wantEndMeeting: "Do you want to end this meeting?",
  gender: "Gender",
  male: "Male",
  female: "Female",
  other: "Other",
  birthDate: "Date of birth",
  city: "City",
  information: "Information",
  saving: "Saving",
  goals: "Achievements",
  workPlaces: "WorkPlaces",
  startPracticingDate: "Date I start practicing",
  aditionalInformation: "Additional Information",
  obtainedDate: "Date obtained",
  title: "Title",
  deleteGoal: "Delete Achievement",
  addGoal: "Add Achievement",
  placeName: "Name of the place",
  workingHour: "Working Hours",
  deleteWorkPlace: "Delete WorkPlace",
  add: "Add",
  sendMessage: "Send a message",
  search: "Search",
  notes: "Notes",
  logout: "Logout",
  psychologistLicensed: "Degree in Psychology",
  psychologist: "Psychologist", 
  experienceYears: "Years of experience", 
  acknowledgments: "Acknowledgments", 
  meeting: "Meeting",
  welcome: "Welcome",
  calendar: "Calendar",
  appointmentsHistory: "Appointments History",
  reunion: "Meeting",
  article: "Article",
  editProfile: "Edit Profile",
  disponibles: "Available",
  startEndDateError: "The start time must be less than the end time, have a minimum difference of 15 minutes and no more than 2 hours.",
  newMeeting: "New Meeting",
  complete: "Complete",
  start: "Start",
  end: "End",
  accept: "Accept",
  newArticle: "New Article",
  loseChanges: "You are going to lose your changes",
  askSaveChanges: "Do you want to save these changes?",
  years: "years",
  example: "The example works",
};
