
export const es = {
  welcomeTo: "Bienvenido a",
  slogan: "Donde tu salud mental es la prioridad.",
  description: "Espacio dedicado a la salud mental y la realización de citas con especialistas del área. Un paso más cerca, sin salir de casa.",
  login: "Inicia sesión",
  register: "Registrate",
  or: "o",
  conditions1: "Al seguir, estás accediendo a los",
  conditions2: "términos y condiciones",
  conditions3: "de la aplicación.",
  loginIncorrect: "Su correo o contraseña son incorrectos. Inténtelo nuevamente.",
  doesNotHasAccount: "¿No tienes una cuenta?",
  email: "Correo electrónico",
  password: "Contraseña",
  accountType: "¿Qué tipo de cuenta vas a utilizar?",
  pacient: "Paciente",
  specialist: "Especialista",
  registerOf: "Registro de",
  name: "Nombre",
  lastName: "Apellido",
  idCard: "Cédula",
  mustContainIdCard: "Debe contener 11 numeros.",
  incorrectEmail: "Correo electrónico incorrecto.",
  includePassword: "Debe de incluir mas de 8 caracteres.",
  mustContainPassword: "Debe incluir almenos una letra mayuscula [A-Z], una letra minuscula [a-z], un numero [0-9] y un signo especial [@$!%*?&].",
  confirmPassword: "Confirma la contraseña",
  noCoincidencePassword: "Contraseñas no coinciden.",
  hasAccount: "¿Ya tienes una cuenta?",
  reunions: "Reuniones",
  needReunion: "¿Necesitas otra reunión?",
  firstAppointment: "¡Nada que mostrar por ahora! \n Agenda tu primera cita para ver información aquí. :)",
  scheduleAppointment: "Agenda una cita",
  hasEmergency: "¿Tienes una emergencia? \n Contactate con uno de nuestros expertos disponibles.",
  takeAppointmentNow: "Ten una cita ahora",
  nothingToSee: "¡Nada que mostrar por ahora! \nSi no lo has hecho, completa tu perfil para que los pacientes sepan mas sobre ti y agenden citas.",
  meetingDetails: "Detalles de la reunión",
  date: "Fecha",
  sessionTime: "Tiempo de la sesión",
  duration: "Duración",
  minutes: "Minutos",
  participants: "Participantes",
  appointmentDescription: "Descripción",
  joinMeeting: "Únete a la reunión",
  askDeleteArticle: "¿Quieres borrar este artículo?",
  deleteArticle: "Borrar Artículo",
  modifyArticle: "Editar Artículo",
  addArticle: "Agregar Artículo",
  cancel: "Cancelar",
  videocall: "Videollamada",
  audiocall: "Llamada de audio",
  writeAMessage: "Escribe un mensaje",
  otherUserGotOut: "El usuario contraparte ha salido de esta reunion",
  incomingVideocall: "Llamada de video entrante",
  incomingAudiocall: "Llamada de audio entrante",
  chatAdvice: "Los mensajes compartidos en este chat son confidenciales. Nadie fuera de la conversación puede leerlos o descifrarlos.",
  connecting: "Conectando",
  waitingForSomebody: "Esperando que alguien mas se una",
  wantEndMeeting: "¿Quieres terminar esta reunion?",
  gender: "Género",
  male: "Masculino",
  female: "Femenino",
  other: "Otro",
  birthDate: "Fecha de nacimiento",
  city: "Ciudad",
  information: "Información",
  saving: "Guardando",
  goals: "Logros",
  workPlaces: "Lugares de Trabajo",
  startPracticingDate: "Fecha en que inicio a ejercer",
  aditionalInformation: "Información adicional",
  obtainedDate: "Fecha obtenido",
  title: "Titulo",
  deleteGoal: "Borrar Logro",
  addGoal: "Agregar Logro",
  placeName: "Nombre del lugar",
  workingHour: "Horario de Trabajo",
  deleteWorkPlace: "Borrar Lugar de Trabajo",
  add: "Agregar",
  sendMessage: "Envia un mensaje",
  search: "Buscar",
  notes: "Notas",
  logout: "Cerrar sesión",
  psychologistLicensed: "Lic. En Psicologia",
  psychologist: "Psicologo",
  experienceYears: "Años de experiencia",
  acknowledgments: "Reconocimientos",
  meeting: "Encuentro",
  welcome: "Bienvenido",
  calendar: "Calendario",
  appointmentsHistory: "Historial de citas",
  reunion: "Reunión",
  article: "Artículo",
  editProfile: "Editar Perfil",
  disponibles: "Disponibles",
  startEndDateError: "La hora de inicio debe ser menor a la de final, tener un minimo de 15 minutos de diferencia y no mayor a 2 horas.",
  newMeeting: "Nueva reunión",
  complete: "Completar",
  start: "Inicio",
  end: "Termina",
  accept: "Aceptar",
  newArticle: "Nuevo Artículo",
  loseChanges: "Vas a perder tus cambios",
  askSaveChanges: "¿Quieres guardar estos cambios?",
  years: "años",
  example: "El ejemplo funciona correctamente",
  loading: "Cargando",
  calling: "Llamando",
  closedCall: "Salió de la llamada"
};
